### PR TITLE
updated CO web l10n

### PR DESCRIPTION
**Pull request by brandelune**
@Patriccollu I think we should be good now. Could you please check?

### CODE REVIEW

**Comment by brandelune** [comment]
@briacp What's the delay to have the data be displayed on the web? I'm not seeing the data yet.

**Comment by briacp** [comment]
> @briacp What's the delay to have the data be displayed on the web? I'm not seeing the data yet.

Around 5mn, maybe there's cached data on your end?

**Comment by brandelune** [comment]
It's on now. Sorry for the hassle and for keeping you up so late. I woke up before 5 this morning, that's why I was able to finish all that. Now I'm exhausted 😄

**Comment by Patriccollu** [comment]
@brandelune @briacp 
The Corsican versione of OmegaT's website is perfect! Thanks to both of you.

Patriccollu.

**Pull request merged**
