### PR TITLE
Add install page SourceForge Doc issue #376

### PR DESCRIPTION
**Pull request by damien-rembert**
This PR adds an "Install" page to the website ([SourceForge documentation task 376](https://sourceforge.net/p/omegat/documentation/376/)). It is part of #65. 
The content should be up to date as it comes from the Install OmegaT section found on this page:
[https://doublet.jp/_omegat/en/how.to.html](https://doublet.jp/_omegat/en/how.to.html).
Deployed my branch [here](https://damien-rembert.github.io/omegat-website/install), don't mind the broken CSS 

Possible future tasks:
I have left the "note" class but not added any special formatting for it (for some reason I couldn't get the integrity checks to work for the css files to work properly).
I have only kept the Install steps but "Running OmegaT" might make a nice addition?

### CODE REVIEW

**Review by briacp — APPROVED** [review]
Looks good, thanks Damien

**Comment by brandelune** [comment]
Very nice. Thank you.
The current "stable" version being 4.3 I guess that's the reason why it's 4.3 that's given on the site.

I don't suppose you're sync'ing with the contents of the manual. Since we're going to have this page in all the languages (and we could have that since the manuals do have that contents at the moment), and the tags in docbook and html are different (hence the translation process would require modifying the tags locally), it could be a good idea to automatically get the contents of a specific HTML ID taken from the processed manual.

What do you think about that ?

**Comment by damien-rembert** [comment]
Sorry, just saw this comment. 
I'm not sure how we could sync this page to the processed manual in a way that wouldn't be too complex to be honest.
The best option I can think of now is that we could probably build this page while processing the manual (and then we'd move it over here manually).
I think it may be best to wait for 6 to be available and then update this page in consequence (maybe make it more general) and point to the updated manual for more details.

**Comment by brandelune** [comment]
I guess it's just a documentation/workflow issue. Maybe we can have a task that exports the DocBook to md and puts it there. Let's put that on the back burner for now.

**Pull request merged**
