### PR TITLE
Update the web site for the 6.0 release

### PR DESCRIPTION
**Pull request by brandelune**
There are a number of important changes in this PR.

Please review carefully.

### CODE REVIEW

**Comment by miurahr** [comment]
Reference to webstart has already disabled with CSS `display:none`. I think it is best.

**Comment by miurahr** [comment]
Latest release 6.1.0 will soo arrive within several months. When released how do you do? Don't use `display: none` trick?

**Comment by brandelune** [comment]
> Latest release 6.1.0 will soo arrive within several months. When released how do you do? Don't use `display: none` trick?

We agreed to not publish webstart any more. There is no need for display:none.

**Comment by brandelune** [comment]
That was in September 2022:
https://github.com/omegat-org/omegat/pull/262

**Comment by briacp** [comment]
We should remove the two first tab in the download selector :
image

And perhaps have only one line for the version (and make it bigger) :
image

Though technically 6.0.0 is the standard, from a user point of view, it's also the latest/newest (and since we only manage a single version, it shouldn't be confusing)

**Comment by briacp** [comment]
I propose this for the index page (no change of text content) in https://github.com/brandelune/omegat-website/pull/1:

image

and for the Download Selector :
image

**Review by briacp — APPROVED** [review]
Great!

**Comment by brandelune** [comment]
@briacp the download selector does not work when macOS is selected as the OS.

**Comment by briacp** [comment]
> @briacp the download selector does not work when macOS is selected as the OS.

Good catch, the selector is looking for a Signed version of the macOS install. I'm fixing it to allow unsigned version if it's the only one available

**Comment by brandelune** [comment]
> > @briacp the download selector does not work when macOS is selected as the OS.
> 
> Good catch, the selector is looking for a Signed version of the macOS install. I'm fixing it to allow unsigned version if it's the only one available

For now. it is. Hopefully we'll have a notarized one for 6.1.

**Comment by brandelune** [comment]
Also, we need to apply the changes to all the localized sites.

**Comment by briacp** [comment]
Yes, it's fixed in 605068303bcc24df0f170779e68f71c44b8bde73 - the localized sites should update as well

**Comment by brandelune** [comment]
> Yes, it's fixed in [6050683](https://github.com/omegat-org/omegat-website/commit/605068303bcc24df0f170779e68f71c44b8bde73) - the localized sites should update as well

But the localized sites still have the "installation type" and "version" tabs.

**Pull request merged**
