### PR TITLE
Prepare release 6.0

### PR DESCRIPTION
**Pull request by miurahr**
- Remove 32bit version on linux
- Update master link
- Update standard version to 6.0.0
- Point latest to 6.1.0 (not yet released)
- Minimum windows version is 8 for Java 11
- Update link to Weekly version

### CODE REVIEW

**Review by brandelune — APPROVED** [review]

**Review by briacp — APPROVED** [review]
LGTM, thanks

**Comment by brandelune** [comment]
Ooops.

We should not have a "Latest" distribution any more.

We should only have a "Standard" version and a "Developper" version.

**Comment by brandelune** [comment]
The localized web site versions will not have the updated link sections. Unless we remove the "latest" section manually.

The temporary solution that I can see would be to have Latest set to 6.0 at least temporarily. And also give a clear indication that "Latest" does not exist any more in the Release notes.

What do you both think ?

@miurahr @briacp

**Comment by brandelune** [comment]
For some reason the download links now use the *http* protocol and not *https*. Which results in "file not found" only for the Windows files. Also, "Mac notarized" does not exist yet.

http://sourceforge.net/projects/omegat/files/OmegaT%20-%20Standard/OmegaT%206.0.0/OmegaT_6.0.0_Windows_Signed.exe/download

http://sourceforge.net/projects/omegat/files/OmegaT%20-%20Standard/OmegaT%206.0.0/OmegaT_6.0.0_Windows_64_Signed.exe/download

http://sourceforge.net/projects/omegat/files/OmegaT%20-%20Standard/OmegaT%206.0.0/OmegaT_6.0.0_Windows_without_JRE_Signed.exe/download

The *http* links for the other files are properly redirected to https and link to the files to download.

**Pull request merged**
